# These should be coming from the config var's
GITHUB_PAGES = True
ALL_NOTES_PAGE_ENABLED = True

HEADER: str = '[//begin]: # "Autogenerated link references for markdown compatibility"'
FOOTER: str = '[//end]: # "Autogenerated link references for markdown compatibility"'
SUPPORTED_FILE_EXT = [".md"]
